/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactMessage {
  'id' : bigint,
  'name' : string,
  'message' : string,
  'phone' : string,
}
export interface Enrollment {
  'age' : bigint,
  'playstyle' : string,
  'medicalProblem' : boolean,
  'name' : string,
  'email' : string,
  'planDuration' : string,
  'address' : string,
  'phone' : string,
  'batchTimeSlot' : string,
  'location' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactMessage' : ActorMethod<[bigint], ContactMessage>,
  'getContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getEnrollments' : ActorMethod<[], Array<Enrollment>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'submitContactMessage' : ActorMethod<[string, string, string], undefined>,
  'submitEnrollment' : ActorMethod<
    [
      string,
      string,
      bigint,
      string,
      string,
      string,
      string,
      string,
      string,
      boolean,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];